### ISSUE TITLE
Issue-13: CRUD parcial de Meta e gamificação

### ISSUE THREAD

**Issue by danielosilva1** [ViniciusRCortez/DietasJa#13]
#### 1. CRUD parcial*:
- [x] Criar entidade Meta;
- [x] Cadastrar/inserir uma nova meta para o usuário *logado*;
- [x] Editar uma meta já cadastrada do usuário *logado*;
- [x] Visualizar a meta do usuário *logado*;
#### 2. Gamificação:
- [x] Criar entidade que implemente as funções de gamificação e contador de calorias consumidas no dia;
- [x] Visualizar progresso diário (quanto da meta diária já foi atingida);
- [x] Visualizar histórico de progresso dos últimos sete dias;
- [x] Implementar um contador de dias consecutivos dentro da meta;
#### 3. Manutenção da Meta:
- [x] Atualizar o contador de consumo diário de calorias após o cadastro/exclusão de uma refeição.

*O delete não será implementado, pois a meta diária deverá ser definida pelo usuário no primeiro acesso e após isso não poderá ficar vazia.
